name: Generate Sitemaps

on:
  push:
    branches:
      - master
  schedule:
    # Run weekly on Sunday at midnight
    - cron: '0 0 * * 0'

permissions:
  contents: write  # Required to push changes back to the repo

jobs:
  generate-sitemaps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Generate sitemaps
        run: python .github/scripts/generate_sitemaps.py

      - name: Update timestamps in sitemaps
        run: |
          TODAY=$(date +'%Y-%m-%d')
          sed -i "s|<lastmod>[^<]*</lastmod>|<lastmod>${TODAY}</lastmod>|g" sitemap.xml || true
          sed -i "s|<lastmod>[^<]*</lastmod>|<lastmod>${TODAY}</lastmod>|g" sitemap-main.xml || true

      - name: Commit and push changes if any
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          git add sitemap.xml sitemap-main.xml
          git diff --quiet && git diff --staged --quiet || git commit -m "Update sitemaps"
          git push origin master
