name: Generate Sitemaps

on:
  # Run when content is added or modified
  push:
    branches: [ main, master ]
    paths:
      - 'ai-llm-blog/**/*.html'
      - 'ai-llm-blog/**/*.md'
      - 'assets/images/**'
      - 'ai-llm-blog/assets/images/**'
      - 'ai-llm-blog/posts/**'
      - 'ai-llm-blog/tutorials/**'
      - 'ai-llm-blog/resources/**'
      - 'ai-llm-blog/community/**'
      - 'ai-llm-blog/help/**'
  
  # Also run on a schedule to ensure sitemaps are up to date
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to track changes
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests
      
      - name: Check for content changes
        id: check-changes
        run: |
          # Get list of changed files in the last commit
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          
          # Check if any content files were changed
          if echo "$CHANGED_FILES" | grep -q -E 'ai-llm-blog/.*\.(html|md|jpg|jpeg|png|gif|svg|webp|mp4|webm|ogg|mov)$|ai-llm-blog/(posts|tutorials|resources|community|help)/|assets/images/|ai-llm-blog/assets/images/'; then
            echo "content_changed=true" >> $GITHUB_OUTPUT
          else
            echo "content_changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Generate sitemaps
        if: steps.check-changes.outputs.content_changed == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
        run: |
          python ./github/scripts/generate_sitemaps.py
      
      - name: Commit sitemap files
        if: steps.check-changes.outputs.content_changed == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are changes to commit
          if git status -s | grep -q "sitemap"; then
            git add sitemap*.xml
            git add ai-llm-blog/sitemap*.xml
            git commit -m "Update sitemaps [skip ci]"
            git push
          else
            echo "No changes to sitemaps detected"
          fi