name: Generate Sitemaps

on:
  push:
    branches:
      - main
  schedule:
    # Run weekly on Sunday at midnight
    - cron: '0 0 * * 0'

jobs:
  generate-sitemaps:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml
      
      - name: Generate sitemaps
        run: python .github/scripts/generate_sitemaps.py
      
      - name: Update timestamps
        run: |
          sed -i "s/<lastmod>[^<]*<\/lastmod>/<lastmod>$(date +'%Y-%m-%d')<\/lastmod>/g" sitemap.xml
          sed -i "s/<lastmod>[^<]*<\/lastmod>/<lastmod>$(date +'%Y-%m-%d')<\/lastmod>/g" sitemap-main.xml
      
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add sitemap.xml sitemap-main.xml
          git diff --quiet && git diff --staged --quiet || git commit -m "Update sitemaps"
          git push