name: Sitemap Monitor

on:
  schedule:
    - cron: '0 3 * * *'     # Daily at 03:00 UTC
  workflow_dispatch:

jobs:
  monitor-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r .github/scripts/requirements.txt

      - name: Write credentials to file
        run: echo "$GOOGLE_API_CREDENTIALS" > client_secret.json
        env:
          GOOGLE_API_CREDENTIALS: ${{ secrets.GOOGLE_API_CREDENTIALS }}

      - name: Environment diagnostic
        run: python .github/scripts/env_diagnostic.py
        
      - name: Debug environment
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Scripts directory contents:"
          ls -la .github/scripts/
          echo "Python version:"
          python --version
          echo "Python executable:"
          which python
          
      - name: Run direct sitemap submit script
        run: python .github/scripts/direct_sitemap_submit.py